# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild_quickstart_build_dockerfile]
FROM eu.gcr.io/db-dev-2f4b-gcplabs-testing2/custom_training_py3104_buster@sha256:c754af42623be05fe7e9699429210af1bb342fa4d7bb26026d9dcf08517de716
COPY quickstart.sh /
CMD ["/quickstart.sh"]

# [END cloudbuild_quickstart_build_dockerfile]
